[package]
name = "alkanes"
version = "0.1.0"
edition = "2021"
description = "ALKANES metaprotocol indexer"
license = "MIT"
repository = "https://github.com/kungfuflex/alkanes-rs"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.89"
bitcoin = { version = "0.30.1", features = ["rand"] }
metashrew = { git = "https://github.com/sandshrewmetaprotocols/metashrew-rs" }
ordinals = { git = "https://github.com/kungfuflex/protorune-rs", branch = "main" }
protorune = { git = "https://github.com/kungfuflex/protorune-rs", branch = "main" }
ruint = "1.12.3"
wasm-bindgen = "0.2.95"
byteorder = "1.5"
wasm-bindgen-test = "0.3.43"
wasmi = "0.37.2"
serde = "1.0.210"
hex = "0.4.3"
protobuf = "3.7.1"

[dev-dependencies]
metashrew = { git = "https://github.com/sandshrewmetaprotocols/metashrew-rs", features = [
    "mock",
] }
wasm-bindgen-cli = "0.2.95"
getrandom = { version = "0.2.15", features = ["js"] }
protorune = { git = "https://github.com/kungfuflex/protorune-rs", features = [
    "test_utils",
], branch = "main" }
[build-dependencies]
protobuf-codegen = "3.4.0"
protoc-rust = { version = "2.28.0" }
protoc-bin-vendored = "3.0.0"
