name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install test runner
        run: cargo install wasm-bindgen-cli --version 0.2.100
      - name: Run wasm tests
        run: cargo test --target wasm32-unknown-unknown --features test-utils
      - name: Run unit tests
        run: cargo test --target x86_64-unknown-linux-gnu  --features test-utils
      - name: Run protorunes wasm tests
        run: cargo test -p protorune --features test-utils
      - name: Run protorune unit tests
        run: cargo test -p protorune --target x86_64-unknown-linux-gnu
